import {ServerBrowser,formatBytes} from './browser.js';
import {Viewer} from './gizmo.js';
import * as M from './pose-math.js';
const $=id=>document.getElementById(id), poseIds=['rx','ry','rz','tx','ty','tz'];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const basename=p=>String(p||'').replace(/\\/g,'/').split('/').pop()||'—';
const fmt=(v,n=3)=>v==null?'—':Number(v).toFixed(n);
let state=null,current=0,context='source',mode='align',tool='translate',space='global',geometry=null,geometryPath=null;
let currentDirectory=null,sourceIdentity=null,imageSignature='',treeSignature='',inspectorSignature='',playing=null;
let localPose=null,pendingPose=null,poseTimer=null,poseWrite=Promise.resolve(),working=0,uploadRequest=null;
let poseSaving=0,imageRequest=0,imageController=null,imageURL=null;
let timelineDrag=null,diagnosticsOpen=false;
const recent=JSON.parse(localStorage.getItem('tracker.projects')||'[]');
function error(message){$('error').hidden=!message;$('error').querySelector('span').textContent=message||'';}
$('error').querySelector('button').onclick=()=>error('');
async function api(path,body){const r=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||r.statusText);return data;}
async function command(path,body={}){working++;syncDisabled();$('saveState').textContent='Сохранение…';try{const result=await api(path,body);if(result.project!==undefined)apply(result);$('saveState').textContent='Сохранено';return result;}catch(e){$('saveState').textContent='Ошибка записи';throw e;}finally{working--;syncDisabled();}}
function action(id,fn){const element=$(id);if(element)element.onclick=async e=>{try{error('');await fn(e);}catch(e){error(e.message);}};}
function bindButton(element,fn){element.onclick=async()=>{try{error('');await fn();}catch(e){error(e.message);}};}
function project(){if(!state?.project)throw new Error('Сначала создайте или откройте проект');return state.project;}
function num(id){const element=$(id);if(!element||element.value.trim()===''||!Number.isFinite(Number(element.value)))throw new Error('Введите число: '+id);return Number(element.value);}
const frames=()=>state?.project?.source.frames||[];
function poseEntry(){const p=state?.project;return p&&(p.drafts[current]||p.anchors[current]||p.poses[current]);}
function matrix(){return localPose||poseEntry()?.matrix||M.fromValues(poseIds.map(id=>Number($(id).value)||0));}
function fillPose(m=matrix()){M.toValues(m).forEach((v,i)=>{$(poseIds[i]).title=v.toFixed(9);if(document.activeElement!==$(poseIds[i]))$(poseIds[i]).value=v.toFixed(5);});}
const viewer=new Viewer({started:()=>updateImage(true,true),changed:m=>{localPose=m;fillPose(m);$('saveState').textContent='Pose изменена';},finished:m=>{queuePose(m);flushPose().catch(e=>error(e.message));}});
const browser=new ServerBrowser(api);
function syncViewer(){viewer.set({camera:state?.project?.camera,matrix:frames().length&&state?.project?.mesh?matrix():null,geometry,enabled:!state?.busy,mode,tool,space});}
async function updateImage(force=false,interactive=false){const p=state?.project;if(!p?.source.frames.length){imageRequest++;imageController?.abort();$('frameImage').removeAttribute('src');$('imageStage').hidden=true;return;}const signature=JSON.stringify([current,state.directory,p.source.path,p.mesh?.prepared,p.camera,p.drafts[current],p.refinements[current],p.poses[current],p.masks,$('showInitial').checked,$('showRefined').checked,$('showObjectMask').checked,$('showOcclusionMask').checked,$('displayMode').value,$('opacity').value]);if(!force&&signature===imageSignature)return;imageSignature=signature;$('imageStage').hidden=false;const params=new URLSearchParams({index:current,initial:interactive?0:+$('showInitial').checked,refined:+$('showRefined').checked,masks:1,object_mask:+$('showObjectMask').checked,occlusion_mask:+$('showOcclusionMask').checked,mode:$('displayMode').value,opacity:$('opacity').value,v:Date.now()});const request=++imageRequest;imageController?.abort();imageController=new AbortController();try{const response=await fetch('/api/frame?'+params,{signal:imageController.signal});if(!response.ok)throw new Error('Не удалось отобразить кадр');const url=URL.createObjectURL(await response.blob());const next=new Image();next.src=url;await next.decode();if(request!==imageRequest){URL.revokeObjectURL(url);return;}const previous=imageURL;imageURL=url;$('frameImage').src=url;if(previous)URL.revokeObjectURL(previous);}catch(e){if(e.name!=='AbortError'&&request===imageRequest){imageSignature='';error(e.message);}} }
$('frameImage').onload=()=>{if(!viewer.drag&&!pendingPose&&!poseSaving)viewer.clearPreview();};
$('frameImage').onerror=()=>{if(frames().length)error('Не удалось отобразить кадр. Проверьте доступность source и размеры масок.');};
async function loadGeometry(){const path=state?.project?.mesh?.prepared||null;if(path===geometryPath)return;geometryPath=path;geometry=null;if(path){const result=await api('geometry');if(path===geometryPath)geometry=result;}syncViewer();}
function setContext(value){context=value;inspectorSignature='';renderTree();renderInspector(true);}
function setMode(value){mode=value;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));if(mode==='align')setContext('camera');else if(mode==='track')setContext('tracking');else setContext('review');syncViewer();}
function setTool(value){tool=value;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===value));syncViewer();}
function setSpace(value){space=value;document.querySelectorAll('[data-space]').forEach(b=>b.classList.toggle('active',b.dataset.space===value));syncViewer();}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));document.querySelectorAll('[data-space]').forEach(b=>b.onclick=()=>setSpace(b.dataset.space));document.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>setContext(b.dataset.select));
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
document.querySelectorAll('.menu button').forEach(b=>b.addEventListener('click',()=>b.closest('details').removeAttribute('open')));
function renderTree(){const p=state?.project;const key=JSON.stringify([context,p?.mesh?.source,p?.source.path,Object.keys(p?.anchors||{}),p?.solutions,p?.exports]);if(key===treeSignature)return;treeSignature=key;const tree=$('projectTree');tree.replaceChildren();
 const group=(title,items)=>{const heading=document.createElement('div');heading.className='treeGroup';heading.textContent='▾ '+title;tree.appendChild(heading);for(const [id,label,meta]of items){const b=document.createElement('button');b.className='treeItem'+(context===id?' selected':'')+(id.startsWith('anchor:')?' anchor':'');b.setAttribute('role','treeitem');b.setAttribute('aria-selected',String(context===id));b.dataset.context=id;const dot=document.createElement('span');dot.className='dot';const text=document.createElement('span');text.textContent=label;const small=document.createElement('small');small.textContent=meta||'';b.append(dot,text,small);b.title=label+(meta?' · '+meta:'');b.onclick=()=>{setContext(id);if(id.startsWith('anchor:'))selectFrame(Number(id.split(':')[1]));};tree.appendChild(b);}};
 group('Media',[['source','Source',p?.source.path?basename(p.source.path):'не задан']]);group('Geometry',[['mesh','Mesh',p?.mesh?basename(p.mesh.source):'не задан']]);group('Camera',[['camera','Camera',p?.camera?`${p.camera.width} × ${p.camera.height}`:'—']]);group('Masks',[['object_mask','Object Mask'],['occlusion_mask','Occlusion Mask']]);group('Tracking',[['tracking','Active Solution'],['solutions','Other Solutions',String(p?.solutions?.length||0)]]);group('Pose Anchors',Object.keys(p?.anchors||{}).sort((a,b)=>a-b).map(i=>['anchor:'+i,'Frame '+i.padStart(4,'0')]));group('Exports',[['exports','Exports',String(p?.exports?.length||0)]]);$('projectLocation').textContent=state?.directory||'Создайте проект через File → New Project';}
function metadata(items){return '<dl class="metadata">'+items.map(([name,value])=>`<dt>${esc(name)}</dt><dd>${esc(value)}</dd>`).join('')+'</dl>';}
function property(label,id,value,step='any'){return `<label class="property">${esc(label)}<input id="${id}" type="number" step="${step}" value="${esc(value)}"></label>`;}
function resources(kind,label){return `<div class="resourceButtons"><button class="replace" id="replaceResource">Replace ${label}…</button><button id="browseResource">Browse Server…</button><button id="uploadResource">Upload…</button></div>`;}
function renderInspector(force=false){const p=state?.project;const signature=JSON.stringify([context,p?.source.path,p?.source.fps,p?.mesh,p?.camera,p?.masks,p?.mask_sources,p?.thresholds,p?.solutions,p?.exports,p?.backend,p?.anchors]);if(!force&&signature===inspectorSignature)return;if(!force&&$('contextProperties').contains(document.activeElement))return;inspectorSignature=signature;const host=$('contextProperties');$('contextTitle').textContent=context.startsWith('anchor:')?'Pose anchor':context.toUpperCase();if(!p){host.innerHTML='<p class="muted">File → New Project / Open Project</p>';return;}
 if(context==='source'){host.innerHTML='<div class="sectionHeading">Source</div>'+metadata([['Name',basename(p.source.path)],['Path',p.source.path||'Не назначен'],['Resolution',p.camera?`${p.camera.width} × ${p.camera.height}`:'—'],['Frames',p.source.frames.length],['Type',p.source.type]])+'<label class="property">Выбор<select id="sourceType"><option value="sequence">Image sequence folder</option><option value="video">Video file</option></select></label>'+resources('source','Source')+property('FPS','sourceFPS',p.source.fps)+ '<button id="applyFPS">Apply FPS</button>';
 action('applyFPS',()=>command('settings',{fps:num('sourceFPS')}));bindResources('source');
 }else if(context==='mesh'){const m=p.mesh;host.innerHTML='<div class="sectionHeading">Mesh</div>'+metadata([['Name',basename(m?.source)],['Path',m?.source||'Не назначен'],['Vertices',m?.vertices??'—'],['Faces',m?.faces??'—'],['Dimensions',m?m.dimensions_mm.map(x=>fmt(x,2)).join(' × ')+' mm':'—'],['Source units',m?.source_units||m?.detected_units||'Не заданы'],['Core units','millimeters']])+resources('mesh','Mesh')+(m?'<label class="property">Source units<select id="meshUnits"><option value="millimeters">Millimeters</option><option value="meters">Meters</option><option value="centimeters">Centimeters</option></select></label><button id="applyMeshUnits">Rebuild with Units</button>'+property('X mm','dimX',m.dimensions_mm[0])+property('Y mm','dimY',m.dimensions_mm[1])+property('Z mm','dimZ',m.dimensions_mm[2])+'<label><input id="center" type="checkbox"> Center at origin</label><div class="row"><button id="prepareMesh">Apply Dimensions</button></div>'+property('Relative ×','meshScale',1)+'<button id="scaleMesh">Apply Relative Scale</button><p class="muted">Множитель текущего размера; повторное применение накапливается.</p>':'');bindResources('mesh');if(m)$('meshUnits').value=m.source_units||m.detected_units||'millimeters';action('applyMeshUnits',()=>replaceResource('mesh',m.source,{units:$('meshUnits').value,center:true}));action('prepareMesh',()=>replaceResource('mesh',m.source,{dimensions:['dimX','dimY','dimZ'].map(num),center:$('center').checked}));action('scaleMesh',()=>replaceResource('mesh',m.source,{scale:num('meshScale'),center:$('center').checked}));
 }else if(context==='camera'){host.innerHTML='<div class="sectionHeading">Pinhole Camera</div>'+(p.camera?metadata([['Resolution',`${p.camera.width} × ${p.camera.height}`],['Coordinates','OpenCV · mm']])+['fx','fy','cx','cy'].map(id=>property(id.toUpperCase(),id,p.camera[id])).join('')+'<button id="camera">Apply Intrinsics</button><hr>'+property('FF equiv. mm','focal',35)+'<button id="estimate">Estimate FX / FY</button><p class="muted">Приближение по ширине 36 mm, не калибровка. '+(p.camera_approximate?'Текущие intrinsics приблизительные.':'')+'</p>':'<p class="muted">Сначала назначьте Source.</p>');action('estimate',()=>{const v=p.camera.width*num('focal')/36;$('fx').value=$('fy').value=v.toFixed(4);});action('camera',async()=>{const camera={...p.camera,...Object.fromEntries(['fx','fy','cx','cy'].map(k=>[k,num(k)]))};const choice=await invalidation('camera');if(choice!==null)await command('resource',{kind:'camera',camera,invalidation:choice});});
 }else if(context==='object_mask'||context==='occlusion_mask'){const kind=context,source=p.mask_sources?.[kind];host.innerHTML='<div class="sectionHeading">'+(kind==='object_mask'?'Object Mask':'Occlusion Mask')+'</div>'+metadata([['Source',source?.directory||'Не назначен'],['Matched',`${Object.keys(p.masks[kind]).length} / ${p.source.frames.length}`],['Missing',p.source.frames.length-Object.keys(p.masks[kind]).length]])+'<label class="property">Match<select id="maskMatch"><option value="filename">Filename stem</option><option value="number">Source frame number</option></select></label>'+resources(kind,'Masks')+'<button id="clearMasks">Clear Layer</button><p class="muted">Отдельный слой '+kind+'. GoTrack baseline не использует маски для refinement.</p>';if(source)$('maskMatch').value=source.mode;bindResources(kind);action('clearMasks',()=>command('masks',{kind,directory:''}));
 }else if(context==='solutions'){host.innerHTML='<div class="sectionHeading">Other Solutions</div><p class="muted">Открытие solution восстанавливает его ресурсы и poses. Текущий контекст также сохраняется.</p>'+p.solutions.map(s=>`<div class="solutionCard"><b>${esc(s.name)}</b><div class="muted">${esc(new Date(s.created).toLocaleString())} · ${s.frames} poses<br>${esc(basename(s.mesh))} · ${esc(basename(s.source))}</div><button data-solution="${esc(s.id)}">Open Solution</button></div>`).join('');host.querySelectorAll('[data-solution]').forEach(b=>bindButton(b,async()=>{await flushPose();localPose=null;await command('solution',{id:b.dataset.solution});fillPose();}));
 }else if(context==='exports'){host.innerHTML='<div class="sectionHeading">Exports</div><div class="row"><button id="export" class="accent">Export Poses</button><button id="preview">Preview MP4</button></div><div class="muted">NPY · NPZ · JSON · CSV<br>Raw T_cam_from_object · OpenCV · mm</div><hr><div class="sectionHeading">Nuke Geometry + Animation</div>'+property('Relative ×','nukeScale',1)+property('First frame','nukeFirstFrame',1,'1')+'<button id="exportNuke" class="accent">Export Nuke Package</button><p class="muted">OBJ + animated Axis + Camera + .nk + ZIP<br>×1 = mm; ×0.001 = meters. Масштабируются mesh и translation. Только принятые / manual poses.</p><div id="downloads"></div>';for(const path of p.exports||[]){const a=document.createElement('a');a.className='exportLink';a.href='/api/download?path='+encodeURIComponent(path);a.textContent=basename(path);a.title=path;$('downloads').appendChild(a);}action('export',()=>command('export'));action('exportNuke',async()=>{await command('export/nuke',{relative_scale:num('nukeScale'),first_frame:num('nukeFirstFrame')});await refresh();});action('preview',()=>command('preview'));
 }else if(context.startsWith('anchor:')){const index=Number(context.split(':')[1]),anchor=p.anchors[index];host.innerHTML='<div class="sectionHeading">Pose Anchor · '+index+'</div>'+metadata([['Source',anchor?.source||'—'],['Frame',index],['File',p.source.frames[index]?.filename||'—']])+'<button id="goAnchor">Go to Frame</button><p class="muted">Измените Current Pose и нажмите Set Anchor для обновления.</p>';action('goAnchor',()=>selectFrame(index));
 }else{host.innerHTML='<div class="sectionHeading">'+(context==='review'?'Review & Diagnostics':'Active Tracking Solution')+'</div>'+metadata([['Backend',p.backend.id],['Version',p.backend.version?.slice(0,12)||'не загружен'],['GPU',p.backend.metadata?.environment?.gpu||'загрузится при Refine'],['Tracked',Object.keys(p.poses).length],['Anchors',Object.keys(p.anchors).length]])+property('Min score','minScore',p.thresholds.min_score)+property('Max ΔT mm','maxDT',p.thresholds.max_translation_mm)+property('Max ΔR °','maxDR',p.thresholds.max_rotation_deg)+'<button id="thresholds">Apply Warning Thresholds</button><p class="muted">Пороги помечают новые результаты; raw poses не изменяются. Диапазон выбирается на timeline.</p><button id="environment">Environment Check</button><pre id="environmentInfo"></pre>';action('thresholds',()=>command('settings',{thresholds:{min_score:num('minScore'),max_translation_mm:num('maxDT'),max_rotation_deg:num('maxDR')}}));action('environment',async()=>{$('environmentInfo').textContent=JSON.stringify(await api('environment'),null,2);});}
 syncDisabled();
}
function bindResources(kind){action('replaceResource',()=>browseResource(kind));action('browseResource',()=>browseResource(kind));action('uploadResource',()=>uploadResource(kind));}
function affected(kind){const p=project();return kind==='camera'?Object.keys(p.poses).length||Object.keys(p.refinements).length:Object.keys(p.poses).length||Object.keys(p.refinements).length||Object.keys(p.drafts).length||Object.keys(p.anchors).length||(kind==='source'&&(p.camera||Object.values(p.masks).some(m=>Object.keys(m).length)));}
async function invalidation(kind){if(!affected(kind))return '';const p=project();$('invalidationText').textContent=kind==='source'?`Новый Source заменит ${basename(p.source.path)}. Камера, masks, anchors и tracking относятся к прежней последовательности.`:kind==='mesh'?`Новый Mesh или его размеры заменят ${basename(p.mesh?.source)}. Ручные poses, anchors и tracking относятся к прежней геометрии.`:'Новые intrinsics изменят соответствие 3D poses изображению. Tracking и pending refinements станут неактуальны; anchors останутся initial poses.';return new Promise(resolve=>{const dialog=$('invalidation');let resolved=false;const close=()=>{if(!resolved){resolved=true;resolve(null);}};dialog.addEventListener('close',close,{once:true});dialog.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>{resolved=true;dialog.close();resolve(b.dataset.decision==='cancel'?null:b.dataset.decision);});dialog.showModal();});}
async function replaceResource(kind,path,options={}){await flushPose();const choice=await invalidation(kind);if(choice===null)return;localPose=null;await command('resource',{kind,path,options,invalidation:choice,fps:state?.project?.source.fps||24});imageSignature='';inspectorSignature='';renderInspector(true);fillPose();}
async function browseResource(kind){const p=project();let options;if(kind==='source'){const video=$('sourceType')?.value==='video';options={title:video?'Select Video':'Select Image Sequence',folder:!video,extensions:video?['.mp4','.mov','.mkv']:[],start:p.source.path};}else if(kind==='mesh')options={title:'Select Mesh',extensions:['.ply','.obj','.glb','.gltf'],start:p.mesh?.source};else options={title:'Select '+kind+' Folder',folder:true,start:p.mask_sources?.[kind]?.directory};const path=await browser.open(options);if(!path)return;if(kind.includes('mask'))await command('masks',{kind,directory:path,mode:$('maskMatch').value});else await replaceResource(kind,path);}
async function uploadResource(kind){project();const input=$('uploadInput');input.value='';input.multiple=kind!=='pose';input.accept=kind==='mesh'?'.ply,.obj,.glb,.gltf,.bin,.png,.jpg,.jpeg,.mtl':kind==='pose'?'.npy':kind==='source'?'.png,.jpg,.jpeg,.mp4,.mov,.mkv':'.png,.jpg,.jpeg';input.onchange=()=>performUpload(kind,[...input.files]).catch(e=>error(e.message));input.click();}
async function performUpload(kind,files){if(!files.length)return;const maskMode=$('maskMatch')?.value||'filename';const meshFiles=files.filter(f=>/\.(ply|obj|glb|gltf)$/i.test(f.name));if(kind==='mesh'&&meshFiles.length!==1)throw new Error('Выберите один mesh и при необходимости его .bin/.mtl/texture файлы');const videos=files.filter(f=>/\.(mp4|mov|mkv)$/i.test(f.name));if(kind==='source'&&videos.length&&(videos.length!==1||files.length!==1))throw new Error('Загрузите одно видео либо несколько кадров');
 const batch=await api('uploads/start',{kind});$('uploadFiles').replaceChildren();files.forEach(f=>{const line=document.createElement('div');line.textContent=f.name+' · '+formatBytes(f.size);$('uploadFiles').appendChild(line);});$('uploadDestination').textContent=batch.directory;$('uploadProgress').max=files.reduce((s,f)=>s+f.size,0);$('uploadProgress').value=0;$('uploadStatus').textContent='Загрузка…';$('cancelUpload').hidden=false;$('closeUpload').hidden=true;$('uploadDialog').showModal();let loaded=0,paths=[];
 try{for(const file of files){const result=await new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();uploadRequest=xhr;xhr.open('POST','/api/upload?'+new URLSearchParams({id:batch.id,name:file.name}));xhr.setRequestHeader('Content-Type','application/octet-stream');xhr.upload.onprogress=e=>{$('uploadProgress').value=loaded+e.loaded;$('uploadStatus').textContent=file.name+' · '+Math.round((loaded+e.loaded)/$('uploadProgress').max*100)+'%';};xhr.onload=()=>{let result;try{result=JSON.parse(xhr.responseText);}catch{reject(new Error('Некорректный ответ upload'));return;}xhr.status===200?resolve(result):reject(new Error(result.error));};xhr.onerror=()=>reject(new Error('Ошибка соединения при upload'));xhr.onabort=()=>reject(new Error('Upload отменён; переданные файлы сохранены, ресурс не заменён'));xhr.send(file);});paths.push(result.path);loaded+=file.size;}
 uploadRequest=null;$('uploadDialog').close();await refresh();if(kind.includes('mask'))await command('masks',{kind,directory:batch.directory,mode:maskMode});else if(kind==='pose'){await command('pose/import',{index:current,path:paths[0]});localPose=null;fillPose();}else await replaceResource(kind,kind==='source'&&!videos.length?batch.directory:kind==='mesh'?paths[files.indexOf(meshFiles[0])]:paths[0]);
 }catch(e){uploadRequest=null;$('uploadStatus').textContent=e.message;$('cancelUpload').hidden=true;$('closeUpload').hidden=false;throw e;}}
action('cancelUpload',()=>uploadRequest?.abort());action('closeUpload',()=>$('uploadDialog').close());$('uploadDialog').addEventListener('cancel',e=>{if(uploadRequest){e.preventDefault();uploadRequest.abort();}});
function queuePose(m,anchor=false){localPose=m;pendingPose={index:current,matrix:M.copy(m),anchor};clearTimeout(poseTimer);$('saveState').textContent='Pose изменена';}
async function flushPose(){clearTimeout(poseTimer);if(pendingPose){const body=pendingPose;pendingPose=null;poseSaving++;poseWrite=poseWrite.catch(()=>{}).then(async()=>{try{await command('pose',body);if(body.index===current&&!viewer.drag&&!pendingPose&&poseSaving===1){localPose=null;fillPose();syncViewer();}}finally{poseSaving--;}if(body.index===current&&!viewer.drag&&!pendingPose&&!poseSaving)updateImage(true);});}return poseWrite;}
async function savePose(anchor=false){queuePose(matrix(),anchor);await flushPose();}
poseIds.forEach(id=>{$(id).oninput=()=>{try{const m=M.fromValues(poseIds.map(num));queuePose(m);syncViewer();viewer.preview(m);poseTimer=setTimeout(()=>flushPose().catch(e=>error(e.message)),350);}catch{}};$(id).onkeydown=e=>{if(e.shiftKey&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();$(id).value=Number($(id).value)+(e.key==='ArrowUp'?1:-1)*Number($(id).step)*.1;$(id).dispatchEvent(new Event('input'));}};});
async function selectFrame(index,persist=true){if(!frames().length)return;await flushPose();current=Math.max(0,Math.min(frames().length-1,Math.round(index)));localPose=null;fillPose();updateDetails();syncViewer();updateImage();drawTimeline();drawGraphs();if(persist)api('frame/select',{index:current}).catch(e=>error(e.message));}
function updateDetails(){const p=state?.project;const frame=p?.source.frames[current];$('frameNumber').value=current;$('frameNumber').max=Math.max(0,frames().length-1);$('frameCount').textContent=frame?`${current+1} / ${frames().length}`:'— / —';$('frameLabel').textContent=frame?`${frame.filename} · source ${frame.source_number??'—'}`:'Source не назначен';$('poseFrame').textContent='Frame '+current;const r=p&&(p.refinements[current]||p.poses[current]);$('currentDiagnostics').textContent=r?`${r.status} · Score ${fmt(r.score)} · ΔT ${fmt(r.translation_delta_mm)} mm · ΔR ${fmt(r.rotation_delta_deg)}°`:'Untracked';$('viewerHUD').textContent=`${mode.toUpperCase()} · ${space.toUpperCase()} · OpenCV / mm`;$('refineInfo').textContent=p?.refinements[current]?'Pending refinement · Accept / Reject':p?.anchors[current]?'Pose anchor · '+p.anchors[current].source:'Object → camera · OpenCV · mm / degrees';syncDisabled();}
function syncDisabled(){const busy=!!state?.busy||working>0,p=state?.project,hasFrames=!!frames().length,ready=hasFrames&&!!p?.mesh;for(const id of ['newProject','openProject','create','anchor','pose','importPose','refine','forwardToolbar','backwardToolbar','track','trackBackward','retrack']){const el=$(id);if(el)el.disabled=busy||(!['newProject','openProject','create'].includes(id)&&(!hasFrames||(['refine','forwardToolbar','backwardToolbar','track','trackBackward','retrack'].includes(id)&&!ready)));}poseIds.forEach(id=>$(id).disabled=busy||!hasFrames);$('contextProperties').querySelectorAll('button,input,select').forEach(el=>el.disabled=busy);$('accept').disabled=busy||!p?.refinements[current];$('reject').disabled=$('accept').disabled;$('cancel').disabled=!busy;$('resume').disabled=busy||!p?.job?.resumable||!['cancelled','failed','interrupted'].includes(p.job.status);}
function apply(value){state=value;const p=value.project;$('backendStatus').textContent=`${p?.backend.id||'GoTrack'} ● ${value.busy?'Working':'Connected'}`;if(value.error)error(value.error);$('projectName').textContent=p?.name||'Без проекта';const sourceKey=JSON.stringify([value.directory,p?.source.path,p?.source.frames.length,p?.camera?.width,p?.camera?.height]);if(sourceKey!==sourceIdentity){sourceIdentity=sourceKey;current=Math.min(p?.current_frame||0,Math.max(0,frames().length-1));localPose=null;$('rangeStart').value=0;$('rangeEnd').value=Math.max(0,frames().length-1);imageSignature='';fillPose();viewer.fitMode=true;}
 if(value.directory&&value.directory!==currentDirectory){currentDirectory=value.directory;recent.unshift({name:p.name,path:value.directory});const seen=new Set();const dedup=recent.filter(x=>!seen.has(x.path)&&seen.add(x.path)).slice(0,8);recent.splice(0,recent.length,...dedup);localStorage.setItem('tracker.projects',JSON.stringify(recent));renderRecent();}
 $('empty').hidden=!!frames().length;if(p&&!frames().length){$('empty').querySelector('p').textContent='Назначьте Source через Project Tree → Browse Server / Upload';}else $('empty').querySelector('p').textContent='Создайте или откройте проект';
 const job=p?.job,done=job?.completed?.length||0,total=job?.indices?.length||1;$('progress').max=value.progress?.total||total;$('progress').value=value.progress?.completed??done;$('jobInfo').textContent=value.activity?`${value.activity} · ${done}/${total}${job?.elapsed?' · '+fmt(job.elapsed/Math.max(done,1),2)+' s/frame':''}`:job?`${job.status} · ${done}/${total}`:'Готово';renderTree();renderInspector();updateDetails();loadGeometry().catch(e=>error(e.message));syncViewer();if(!viewer.drag&&!pendingPose&&!poseSaving)updateImage();drawTimeline();drawGraphs();if(!working&&!pendingPose)$('saveState').textContent=p?'Сохранено':'—';}
async function refresh(){apply(await api('state'));}
async function poll(){try{await refresh();}catch(e){$('backendStatus').textContent='● Offline';error(e.message);}finally{setTimeout(poll,1200);}}
function renderRecent(){const host=$('recentProjects');host.replaceChildren();recent.slice(0,6).forEach(item=>{const b=document.createElement('button');b.textContent=item.name;b.title=item.path;bindButton(b,async()=>{stopPlay();await flushPose();await command('open',{directory:item.path});});host.appendChild(b);});}
function newProject(){$('projectDialog').showModal();}
async function openProject(){const path=await browser.open({title:'Open Project',project:true,start:state?.directory});if(path){stopPlay();await flushPose();await command('open',{directory:path});}}
for(const id of ['newProject','emptyNew'])action(id,newProject);for(const id of ['openProject','emptyOpen'])action(id,openProject);
action('chooseProjectFolder',async()=>{const path=await browser.open({title:'Project Parent Directory',folder:true,start:state?.directory});if(path)$('directory').value=path;});
$('projectForm').onsubmit=async e=>{e.preventDefault();try{const name=$('name').value.trim();if(!name||/[\\/]/.test(name)||name==='.'||name==='..')throw new Error('Введите имя проекта без / и \\');if(!$('directory').value)throw new Error('Выберите родительский каталог через Browse Server');await flushPose();await command('create',{name,directory:$('directory').value.replace(/\/$/,'')+'/'+name,fps:num('fps')});$('projectDialog').close();setContext('source');}catch(e){error(e.message);}};
for(const id of ['save','saveMenu'])action(id,async()=>{await flushPose();await command('save');});
action('pose',()=>savePose());action('anchor',()=>savePose(true));action('resetDraft',async()=>{const saved=project().anchors[current]||project().poses[current];if(!saved)throw new Error('На кадре нет сохранённой pose');queuePose(saved.matrix);await flushPose();});
action('importPose',async()=>{const path=await browser.open({title:'Import Pose',extensions:['.npy'],start:state?.directory});if(path){await flushPose();localPose=null;await command('pose/import',{index:current,path});fillPose();}});
action('refine',async()=>{stopPlay();await flushPose();if(!poseEntry())await savePose();await command('refine',{index:current});});action('accept',async()=>{await command('accept',{index:current});localPose=null;fillPose();syncViewer();});action('reject',()=>command('reject',{index:current}));
async function track(direction=1){stopPlay();await flushPose();let start=num('rangeStart'),end=num('rangeEnd');[start,end]=direction>0?[Math.min(start,end),Math.max(start,end)]:[Math.max(start,end),Math.min(start,end)];await command('track',{start,end,respect_anchors:$('respectAnchors').checked});}
for(const id of ['track','forwardToolbar','retrack'])action(id,()=>track(1));for(const id of ['trackBackward','backwardToolbar'])action(id,()=>track(-1));action('cancel',()=>command('cancel'));action('resume',()=>command('resume'));
action('setStart',()=>{$('rangeStart').value=current;drawTimeline();});action('setEnd',()=>{$('rangeEnd').value=current;drawTimeline();});for(const id of ['rangeStart','rangeEnd'])$(id).onchange=drawTimeline;
action('first',()=>selectFrame(0));action('last',()=>selectFrame(frames().length-1));action('prev',()=>selectFrame(current-1));action('next',()=>selectFrame(current+1));$('frameNumber').onchange=()=>selectFrame(num('frameNumber')).catch(e=>error(e.message));
function stopPlay(){if(playing){clearInterval(playing);playing=null;}$('play').textContent='▶';}
function play(){if(playing){stopPlay();return;}if(!frames().length)return;$('play').textContent='Ⅱ';playing=setInterval(()=>{if(current>=frames().length-1){stopPlay();return;}selectFrame(current+1,false);},1000/Math.min(12,project().source.fps));}action('play',play);
for(const id of ['fit','fitMenu'])action(id,()=>viewer.fit());action('oneToOne',()=>viewer.one());
for(const id of ['showInitial','showRefined','showObjectMask','showOcclusionMask','displayMode','opacity'])$(id).onchange=()=>updateImage(true);
$('viewPreset').onchange=()=>{const v=$('viewPreset').value;$('showInitial').checked=['both','initial'].includes(v);$('showRefined').checked=['both','refined'].includes(v);if(v==='rgb'){$('showObjectMask').checked=false;$('showOcclusionMask').checked=false;}updateImage(true);};
function prepareCanvas(id){const c=$(id),dpr=devicePixelRatio;c.width=c.clientWidth*dpr;c.height=c.clientHeight*dpr;const ctx=c.getContext('2d');ctx.scale(dpr,dpr);return[c,ctx,c.clientWidth,c.clientHeight];}
const trackNames=['Frames','Tracking','Anchors','Object Mask','Occlusion Mask'];
function timelineMetrics(){const c=$('timeline'),n=Math.max(1,frames().length),left=115,width=Math.max(1,c.clientWidth-left-12);return{left,width,n,row:c.clientHeight/5,step:width/n};}
function drawTimeline(){const[c,ctx,w,h]=prepareCanvas('timeline'),p=state?.project,{left,width,n,row,step}=timelineMetrics();ctx.font='11px Arial';ctx.fillStyle='#2e3033';ctx.fillRect(0,0,w,h);let start=Number($('rangeStart').value)||0,end=Number($('rangeEnd').value)||0;const low=Math.min(start,end),high=Math.max(start,end);ctx.fillStyle='#69604d55';ctx.fillRect(left+low*step,0,(high-low+1)*step,h);trackNames.forEach((name,i)=>{ctx.fillStyle='#303236';ctx.fillRect(0,i*row,left,row);ctx.fillStyle='#aeb5bd';ctx.fillText(name,10,i*row+row/2+4);ctx.strokeStyle='#202224';ctx.beginPath();ctx.moveTo(0,(i+1)*row);ctx.lineTo(w,(i+1)*row);ctx.stroke();});
 if(p){for(let i=0;i<n;i++){const x=left+i*step,entry=p.poses[i],failed=p.job?.status==='failed'&&p.job.indices?.[p.job.completed.length]===i;ctx.fillStyle=failed?'#d2615c':({TRACKED:'#57af75',WARNING:'#dfbd57',FAILED:'#d2615c',MANUAL:'#56b3eb'}[entry?.status]||'#555960');ctx.fillRect(x+1,row+5,Math.max(1,step-2),Math.max(2,row-10));if(p.anchors[i]){ctx.fillStyle='#59b6f1';ctx.beginPath();ctx.moveTo(x+step/2,2*row+4);ctx.lineTo(x+step/2+5,2.5*row);ctx.lineTo(x+step/2,3*row-4);ctx.lineTo(x+step/2-5,2.5*row);ctx.closePath();ctx.fill();}for(const[k,j]of[['object_mask',3],['occlusion_mask',4]]){ctx.fillStyle=p.masks[k][i]?(j===3?'#5a9caa':'#a176aa'):'#46494d';ctx.fillRect(x+1,j*row+7,Math.max(1,step-2),Math.max(2,row-14));}}
 const interval=Math.max(1,Math.ceil(n/Math.max(1,width/55)));for(let i=0;i<n;i+=interval){ctx.fillStyle='#9ca5b0';ctx.fillText(String(i),left+i*step+2,row/2+4);}}
 for(const[index,label]of[[low,'IN'],[high+1,'OUT']]){const x=left+index*step;ctx.fillStyle='#b8a279';ctx.fillRect(x-1,0,2,h);ctx.fillRect(x-4,0,8,8);ctx.font='9px Arial';ctx.fillText(label,x+5,9);}
 const x=left+(current+.5)*step;ctx.strokeStyle='#eee0bb';ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();ctx.fillStyle='#eee0bb';ctx.beginPath();ctx.moveTo(x-5,0);ctx.lineTo(x+5,0);ctx.lineTo(x,7);ctx.fill();}
function frameAt(e){const rect=$('timeline').getBoundingClientRect(),m=timelineMetrics();return Math.max(0,Math.min(m.n-1,Math.floor((e.clientX-rect.left-m.left)/m.step)));}
$('timeline').onpointerdown=e=>{if(!frames().length)return;const rect=e.currentTarget.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top,m=timelineMetrics();if(x<m.left)return;const a=Math.min(num('rangeStart'),num('rangeEnd')),b=Math.max(num('rangeStart'),num('rangeEnd'));let kind=Math.abs(x-(m.left+a*m.step))<7?'start':Math.abs(x-(m.left+(b+1)*m.step))<7?'end':y<m.row?'range':'scrub';timelineDrag={kind,start:frameAt(e),x:e.clientX,moved:false};e.currentTarget.setPointerCapture(e.pointerId);};
$('timeline').onpointermove=e=>{if(!timelineDrag)return;const d=timelineDrag,index=frameAt(e);if(Math.abs(e.clientX-d.x)>4)d.moved=true;if(d.kind==='start')$('rangeStart').value=index;else if(d.kind==='end')$('rangeEnd').value=index;else if(d.kind==='range'&&d.moved){$('rangeStart').value=Math.min(d.start,index);$('rangeEnd').value=Math.max(d.start,index);}drawTimeline();};
$('timeline').onpointerup=e=>{if(!timelineDrag)return;const d=timelineDrag;timelineDrag=null;if(!d.moved||d.kind==='scrub')selectFrame(frameAt(e)).catch(e=>error(e.message));e.currentTarget.releasePointerCapture(e.pointerId);drawTimeline();};$('timeline').onpointercancel=()=>timelineDrag=null;
function drawGraphs(){if(!diagnosticsOpen)return;const p=state?.project,n=Math.max(1,frames().length);for(const[id,key,label]of[['scoreGraph','score','Score'],['translationGraph','translation_delta_mm','ΔT mm'],['rotationGraph','rotation_delta_deg','ΔR °']]){if($(id).hidden)continue;const[c,ctx,w,h]=prepareCanvas(id);const values=Array.from({length:n},(_,i)=>p?.poses[i]?.[key]);const max=Math.max(key==='score'?1:.001,...values.filter(v=>v!=null));ctx.font='11px Arial';ctx.fillStyle='#aab2be';ctx.fillText(label+' · max '+fmt(max,2),8,15);ctx.strokeStyle='#76a9c8';ctx.lineWidth=1.3;ctx.beginPath();let active=false;values.forEach((v,i)=>{if(v==null){active=false;return;}const x=i*w/Math.max(1,n-1),y=h-8-v/max*(h-28);active?ctx.lineTo(x,y):ctx.moveTo(x,y);active=true;});ctx.stroke();ctx.strokeStyle='#b8a577';ctx.beginPath();ctx.moveTo(current*w/Math.max(1,n-1),0);ctx.lineTo(current*w/Math.max(1,n-1),h);ctx.stroke();}}
function toggleDiagnostics(){diagnosticsOpen=!diagnosticsOpen;$('diagnosticsPanel').classList.toggle('open',diagnosticsOpen);$('toggleDiagnostics').textContent=(diagnosticsOpen?'▾':'▸')+' Diagnostics';drawGraphs();saveLayout();}
for(const id of ['toggleDiagnostics','diagnosticsMenu'])action(id,toggleDiagnostics);document.querySelectorAll('[data-graph]').forEach(input=>input.onchange=()=>{$(input.dataset.graph).hidden=!input.checked;drawGraphs();});for(const id of ['scoreGraph','translationGraph','rotationGraph'])$(id).onclick=e=>selectFrame(Math.round((e.clientX-e.currentTarget.getBoundingClientRect().left)/e.currentTarget.clientWidth*(frames().length-1))).catch(e=>error(e.message));
function saveLayout(){const css=document.documentElement.style;localStorage.setItem('tracker.layout',JSON.stringify({left:css.getPropertyValue('--left'),right:css.getPropertyValue('--right'),timeline:css.getPropertyValue('--timeline'),diagnostics:css.getPropertyValue('--diagnostics'),open:diagnosticsOpen}));}
function split(id,variable,axis,inverse,min,max){const el=$(id);let drag;el.onpointerdown=e=>{drag={point:axis==='x'?e.clientX:e.clientY,value:parseFloat(getComputedStyle(document.documentElement).getPropertyValue(variable))};el.classList.add('dragging');el.setPointerCapture(e.pointerId);};el.onpointermove=e=>{if(!drag)return;const delta=(axis==='x'?e.clientX:e.clientY)-drag.point;document.documentElement.style.setProperty(variable,Math.max(min,Math.min(max,drag.value+delta*inverse))+'px');drawTimeline();drawGraphs();};el.onpointerup=e=>{drag=null;el.classList.remove('dragging');el.releasePointerCapture(e.pointerId);saveLayout();};}
split('leftSplitter','--left','x',1,145,400);split('rightSplitter','--right','x',-1,260,460);split('timelineSplitter','--timeline','y',-1,155,350);split('diagnosticsSplitter','--diagnostics','y',-1,90,280);action('resetLayout',()=>{localStorage.removeItem('tracker.layout');for(const k of ['left','right','timeline','diagnostics'])document.documentElement.style.removeProperty('--'+k);drawTimeline();drawGraphs();});
try{const layout=JSON.parse(localStorage.getItem('tracker.layout')||'{}');for(const key of ['left','right','timeline','diagnostics'])if(layout[key])document.documentElement.style.setProperty('--'+key,layout[key]);if(layout.open)toggleDiagnostics();}catch{}
window.addEventListener('resize',()=>{drawTimeline();drawGraphs();});
window.addEventListener('keydown',e=>{const editing=e.target.matches('input,select,textarea')||e.target.isContentEditable,dialog=!!document.querySelector('dialog[open]');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();if(state?.project){flushPose().then(()=>command('save')).catch(e=>error(e.message));}return;}if(editing||dialog)return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();selectFrame(current+(e.key==='ArrowLeft'?-1:1)).catch(e=>error(e.message));}else if(e.code==='Space'){e.preventDefault();play();}else if(e.key.toLowerCase()==='w')setTool('translate');else if(e.key.toLowerCase()==='e')setTool('rotate');else if(e.key.toLowerCase()==='l')setSpace('local');else if(e.key.toLowerCase()==='g')setSpace('global');});
for(const id of ['rx','tx','ry','ty','rz','tz'])document.querySelector('.poseGrid').appendChild($(id).parentElement);
renderRecent();renderTree();poll();
