'use strict';
const $ = id => document.getElementById(id);
let state=null, current=0, playing=null, poseTimer=null, browseTarget=null, lastProject=null, lastSignature='', pendingPose=null, poseWrite=Promise.resolve();
const poseIds=['rx','ry','rz','tx','ty','tz'];
function error(message){$('error').textContent=message||'';$('error').hidden=!message;}
async function api(path,body){const response=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||response.statusText);return result;}
function action(id,fn){$(id).onclick=async()=>{try{error('');await fn();}catch(e){error(e.message);}};}
function num(id){const n=Number($(id).value);if(!Number.isFinite(n))throw new Error('Введите конечное число: '+id);return n;}
function project(){if(!state?.project)throw new Error('Сначала создайте или откройте проект');return state.project;}
async function command(path,body={}){const value=await api(path,body);if(value.project!==undefined)apply(value);return value;}
function poseEntry(){const p=state?.project;if(!p)return null;return p.drafts[current]||p.anchors[current]||p.poses[current];}
function fillPose(){const entry=poseEntry();if(!entry)return;const m=entry.matrix, ry=Math.asin(Math.max(-1,Math.min(1,-m[2][0])));let rx,rz;if(Math.abs(Math.cos(ry))>1e-6){rx=Math.atan2(m[2][1],m[2][2]);rz=Math.atan2(m[1][0],m[0][0]);}else{rx=Math.atan2(-m[1][2],m[1][1]);rz=0;}const values=[rx*180/Math.PI,ry*180/Math.PI,rz*180/Math.PI,m[0][3],m[1][3],m[2][3]];poseIds.forEach((id,i)=>$(id).value=values[i].toFixed(5));}
function updateImage(){if(!state?.project)return;const params=new URLSearchParams({index:current,initial:+$('showInitial').checked,refined:+$('showRefined').checked,masks:+$('showMasks').checked,object_mask:+$('showObjectMask').checked,occlusion_mask:+$('showOcclusionMask').checked,mode:$('displayMode').value,opacity:$('opacity').value,v:Date.now()});$('frameImage').src='/api/frame?'+params;}
function selectFrame(index,persist=true){if(pendingPose)flushPose().catch(e=>error(e.message));const p=project();current=Math.max(0,Math.min(p.source.frames.length-1,Math.round(index)));$('timeline').value=current;$('frameNumber').value=current;fillPose();updateDetails();updateImage();drawGraphs();if(persist)api('frame/select',{index:current}).catch(e=>error(e.message));}
function updateDetails(){const p=state?.project;if(!p)return;const frame=p.source.frames[current];$('frameLabel').textContent=`${frame.filename} · source ${frame.source_number??'—'} · ${current+1}/${p.source.frames.length}`;const r=p.refinements[current]||p.poses[current];const f=x=>x==null?'—':Number(x).toFixed(3);$('currentDiagnostics').textContent=r?`${r.status} · score ${f(r.score)} · dT ${f(r.translation_delta_mm)} мм · dR ${f(r.rotation_delta_deg)}° · ${f(r.runtime)} с`:'Кадр не отслежен';$('refineInfo').textContent=p.refinements[current]?'Refinement ожидает принятия. Initial — жёлтый, результат — зелёный.':p.anchors[current]?'На кадре сохранён pose anchor.':'';$('accept').disabled=state.busy||!p.refinements[current];$('reject').disabled=state.busy||!p.refinements[current];$('maskInfo').textContent=['object_mask','occlusion_mask'].map(k=>`${k}: ${Object.keys(p.masks[k]).length}/${p.source.frames.length}; текущий ${p.masks[k][current]?'есть':'отсутствует'}`).join('\n');}
function apply(value){const before=state;state=value;$('connection').textContent=value.busy?'Выполняется операция':'Подключено';if(value.error)error(value.error);const p=value.project;if(!p)return;const newProject=lastProject!==value.directory;lastProject=value.directory;$('empty').hidden=true;$('projectName').textContent=p.name;$('timeline').max=p.source.frames.length-1;$('frameNumber').max=p.source.frames.length-1;
 if(newProject){current=p.current_frame||0;$('directory').value=value.directory;$('openDirectory').value=value.directory;$('source').value=p.source.path;$('mesh').value=p.mesh.source;$('name').value=p.name;$('rangeStart').value=current;$('rangeEnd').value=p.source.frames.length-1;$('fps').value=p.source.fps;$('objectMask').value=p.mask_sources?.object_mask?.directory||'';$('occlusionMask').value=p.mask_sources?.occlusion_mask?.directory||'';['fx','fy','cx','cy'].forEach(k=>$(k).value=p.camera[k]);['dimX','dimY','dimZ'].forEach((k,i)=>$(k).value=p.mesh.dimensions_mm[i]);$('minScore').value=p.thresholds.min_score;$('maxDT').value=p.thresholds.max_translation_mm;$('maxDR').value=p.thresholds.max_rotation_deg;fillPose();}
 $('timeline').value=current;$('frameNumber').value=current;$('meshInfo').textContent=`${p.mesh.vertices} вершин · ${p.mesh.faces} faces · ${p.mesh.dimensions_mm.map(x=>x.toFixed(2)).join(' × ')} мм`;
 const job=p.job;const total=job?.indices?.length||1,done=job?.completed?.length||0;$('progress').max=value.progress?.total||total;$('progress').value=value.progress?.completed||done;
 $('jobInfo').textContent=value.activity?`${value.activity} · ${done}/${total}${job?.current_frame!=null?' · кадр '+job.current_frame:''}${job?.score!=null?' · score '+job.score.toFixed(3):''}${job?.elapsed?' · '+(job.elapsed/Math.max(done,1)).toFixed(2)+' с/кадр':''}`:job?`${job.status} · ${done}/${total} · ${(job.elapsed||0).toFixed(1)} с inference`:'Нет активного задания';
 ['create','open','pose','anchor','importPose','refine','track','prepareMesh','scaleMesh','camera','masks','export','preview','thresholds'].forEach(id=>$(id).disabled=value.busy);poseIds.forEach(id=>$(id).disabled=value.busy);$('cancel').disabled=!value.busy;$('resume').disabled=value.busy||!job?.resumable||!['cancelled','interrupted','failed'].includes(job.status);updateDetails();drawGraphs();const signature=JSON.stringify([value.directory,current,p.drafts[current],p.poses[current],p.refinements[current],p.masks,p.camera,p.mesh.prepared]);if(signature!==lastSignature){lastSignature=signature;updateImage();}if(p.last_preview&&p.last_preview!==before?.project?.last_preview)addDownload(p.last_preview);
}
function canvas(id){const c=$(id);c.width=Math.max(1,c.clientWidth*devicePixelRatio);const ctx=c.getContext('2d');return [c,ctx];}
function drawGraphs(){const p=state?.project;if(!p)return;const n=p.source.frames.length;{const[c,ctx]=canvas('statusStrip');for(let i=0;i<n;i++){const status=p.poses[i]?.status;ctx.fillStyle=p.anchors[i]?'#59b9ed':({TRACKED:'#46a870',WARNING:'#d5aa42',FAILED:'#d55858',MANUAL:'#59b9ed'}[status]||'#343c48');ctx.fillRect(i*c.width/n,0,Math.ceil(c.width/n),c.height);}ctx.fillStyle='white';ctx.fillRect(current*c.width/n,0,2*devicePixelRatio,c.height);}
 for(const[id,key]of[['scoreGraph','score'],['translationGraph','translation_delta_mm'],['rotationGraph','rotation_delta_deg']]){const[c,ctx]=canvas(id);const values=Array.from({length:n},(_,i)=>p.poses[i]?.[key]);const max=Math.max(key==='score'?1:0.001,...values.filter(v=>v!=null));ctx.strokeStyle='#68bcea';ctx.lineWidth=2;ctx.beginPath();let active=false;values.forEach((v,i)=>{if(v==null){active=false;return;}const x=i*c.width/Math.max(1,n-1),y=c.height-8-v/max*(c.height-20);if(active)ctx.lineTo(x,y);else ctx.moveTo(x,y);active=true;});ctx.stroke();ctx.fillStyle='#aabbd0';ctx.font='12px sans-serif';ctx.fillText(max.toFixed(2),6,13);ctx.fillStyle='#ffffff88';ctx.fillRect(current*c.width/Math.max(1,n-1),0,1,c.height);}}
async function flushPose(){clearTimeout(poseTimer);if(pendingPose){const body=pendingPose;pendingPose=null;poseWrite=poseWrite.catch(()=>{}).then(()=>command('pose',body));}return poseWrite;}
async function savePose(anchor=false){pendingPose={index:current,values:poseIds.map(num),anchor};return flushPose();}
poseIds.forEach(id=>$(id).addEventListener('input',()=>{clearTimeout(poseTimer);pendingPose={index:current,values:poseIds.map(num),anchor:false};poseTimer=setTimeout(()=>flushPose().catch(e=>error(e.message)),350);}));
action('create',async()=>{stopPlay();await flushPose();await command('create',{directory:$('directory').value,source:$('source').value,mesh:$('mesh').value,name:$('name').value,fps:num('fps')});});
action('open',async()=>{stopPlay();await flushPose();await command('open',{directory:$('openDirectory').value});});
action('save',()=>command('save'));action('pose',()=>savePose());action('anchor',()=>savePose(true));
action('importPose',async()=>{await command('pose/import',{index:current,path:$('posePath').value});fillPose();});
action('refine',async()=>{stopPlay();await flushPose();if(!poseEntry())await savePose();await command('refine',{index:current});});
action('accept',async()=>{await command('accept',{index:current});fillPose();});action('reject',()=>command('reject',{index:current}));
action('camera',()=>command('settings',{camera:{...project().camera,...Object.fromEntries(['fx','fy','cx','cy'].map(k=>[k,num(k)]))}}));
action('estimate',()=>{const focal=project().camera.width*num('focal')/36;$('fx').value=$('fy').value=focal.toFixed(4);});
action('prepareMesh',()=>command('settings',{mesh:{source:$('mesh').value,dimensions:['dimX','dimY','dimZ'].map(num),center:$('center').checked}}));
action('scaleMesh',()=>command('settings',{mesh:{source:$('mesh').value,scale:num('meshScale'),center:$('center').checked}}));
action('masks',async()=>{await command('masks',{kind:'object_mask',directory:$('objectMask').value,mode:$('maskMatch').value});await command('masks',{kind:'occlusion_mask',directory:$('occlusionMask').value,mode:$('maskMatch').value});});
action('thresholds',()=>command('settings',{thresholds:{min_score:num('minScore'),max_translation_mm:num('maxDT'),max_rotation_deg:num('maxDR')}}));
action('track',async()=>{stopPlay();await flushPose();await command('track',{start:num('rangeStart'),end:num('rangeEnd'),respect_anchors:$('respectAnchors').checked});});
action('cancel',()=>command('cancel'));action('resume',()=>command('resume'));
function addDownload(path){const a=document.createElement('a');a.href='/api/download?path='+encodeURIComponent(path);a.textContent=path.split('/').pop();$('downloads').appendChild(a);}
action('export',async()=>{const result=await command('export');$('downloads').replaceChildren();result.files.forEach(addDownload);});action('preview',()=>command('preview'));
action('environment',async()=>{$('environmentInfo').textContent=JSON.stringify(await api('environment'),null,2);});
action('prev',()=>selectFrame(current-1));action('next',()=>selectFrame(current+1));action('setStart',()=>{$('rangeStart').value=current;});action('setEnd',()=>{$('rangeEnd').value=current;});
$('timeline').oninput=()=>selectFrame(num('timeline'),false);$('timeline').onchange=()=>selectFrame(num('timeline'));$('frameNumber').onchange=()=>{try{selectFrame(num('frameNumber'));}catch(e){error(e.message);}};
function stopPlay(){if(playing){clearInterval(playing);playing=null;$('play').textContent='▶ Воспроизвести';}}
action('play',()=>{if(playing){stopPlay();return;}const p=project();$('play').textContent='⏸ Пауза';playing=setInterval(()=>{if(current>=p.source.frames.length-1){stopPlay();return;}selectFrame(current+1,false);},1000/Math.min(12,p.source.fps));});
['showInitial','showRefined','showMasks','showObjectMask','showOcclusionMask','displayMode','opacity'].forEach(id=>$(id).onchange=updateImage);
['statusStrip','scoreGraph','translationGraph','rotationGraph'].forEach(id=>$(id).onclick=e=>{if(state?.project){const ratio=(e.clientX-e.currentTarget.getBoundingClientRect().left)/e.currentTarget.clientWidth;selectFrame(Math.floor(ratio*state.project.source.frames.length));}});
async function browse(path){const value=await api('browse?path='+encodeURIComponent(path||''));$('browsePath').value=value.path;$('browseEntries').replaceChildren();$('browseUp').onclick=()=>browse(value.parent).catch(e=>error(e.message));for(const entry of value.entries){const b=document.createElement('button');b.textContent=(entry.directory?'📁 ':'')+entry.name;b.onclick=()=>{if(entry.directory)browse(entry.path).catch(e=>error(e.message));else{$(browseTarget).value=entry.path;$('browser').close();}};$('browseEntries').appendChild(b);}}
document.querySelectorAll('[data-browse]').forEach(b=>b.onclick=async()=>{browseTarget=b.dataset.browse;try{await browse($(browseTarget).value);$('browser').showModal();}catch(e){error(e.message);await browse('');$('browser').showModal();}});
action('browseGo',()=>browse($('browsePath').value));action('browseSelect',()=>{$(browseTarget).value=$('browsePath').value;$('browser').close();});action('browseClose',()=>$('browser').close());
$('frameImage').onerror=()=>error('Не удалось отобразить кадр. Проверьте доступность input и размеры масок.');
window.addEventListener('resize',drawGraphs);
async function poll(){try{apply(await api('state'));}catch(e){$('connection').textContent='Нет соединения';error(e.message);}finally{setTimeout(poll,1200);}}
poll();
