import * as M from './pose-math.js';
const colors=['#ec6b66','#75cf88','#6aa7f4'];
function distanceToSegment(p,a,b){const d=M.sub(b,a),q=M.sub(p,a),t=Math.max(0,Math.min(1,M.dot(q,d)/(M.dot(d,d)||1)));return M.norm(M.sub(p,M.add(a,M.scale(d,t))));}
export class Viewer {
  constructor({changed,finished,started}) {
    this.changed=changed;this.finished=finished;this.started=started;this.el=document.getElementById('viewport');this.canvas=document.getElementById('gizmo');this.stage=document.getElementById('imageStage');this.overlay=document.getElementById('poseOverlay');
    this.zoom=1;this.pan=[0,0];this.fitMode=true;this.tool='translate';this.space='global';this.handles=[];this.matrix=null;this.geometry=null;this.enabled=true;
    new ResizeObserver(()=>{if(this.fitMode)this.fit();else this.draw();}).observe(this.el);
    this.canvas.onwheel=e=>{e.preventDefault();const point=this.point(e),before=this.imagePoint(point);this.zoom=Math.max(.03,Math.min(12,this.zoom*Math.exp(-e.deltaY*.001)));this.pan=M.sub(point,M.scale(before,this.zoom));this.fitMode=false;this.draw();};
    this.canvas.onpointerdown=e=>this.down(e);this.canvas.onpointermove=e=>this.move(e);this.canvas.onpointerup=e=>this.up(e);this.canvas.onpointercancel=e=>this.up(e);this.canvas.oncontextmenu=e=>e.preventDefault();
  }
  set({camera,matrix,geometry,enabled,mode,tool,space}){const newCamera=JSON.stringify(camera)!==JSON.stringify(this.camera);this.camera=camera;this.matrix=matrix;this.geometry=geometry;this.enabled=enabled;this.mode=mode;this.tool=tool;this.space=space;if(newCamera)this.fit();else this.draw();}
  point(e){const box=this.canvas.getBoundingClientRect();return[e.clientX-box.left,e.clientY-box.top];}
  imagePoint(p){return M.scale(M.sub(p,this.pan),1/this.zoom);}
  screen(p){const uv=M.project(p,this.camera);return uv?M.add(M.scale(uv,this.zoom),this.pan):null;}
  fit(){if(!this.camera)return;this.zoom=Math.min(this.el.clientWidth/this.camera.width,this.el.clientHeight/this.camera.height)*.98;this.pan=[(this.el.clientWidth-this.camera.width*this.zoom)/2,(this.el.clientHeight-this.camera.height*this.zoom)/2];this.fitMode=true;this.draw();}
  one(){if(!this.camera)return;this.zoom=1;this.pan=[(this.el.clientWidth-this.camera.width)/2,(this.el.clientHeight-this.camera.height)/2];this.fitMode=false;this.draw();}
  draw(){const width=this.el.clientWidth,height=this.el.clientHeight,dpr=devicePixelRatio;this.canvas.width=width*dpr;this.canvas.height=height*dpr;const ctx=this.canvas.getContext('2d');ctx.scale(dpr,dpr);this.handles=[];if(!this.camera)return;this.stage.style.width=this.camera.width+'px';this.stage.style.height=this.camera.height+'px';this.stage.style.transform=`translate(${this.pan[0]}px,${this.pan[1]}px) scale(${this.zoom})`;document.getElementById('zoomLabel').textContent=(this.zoom*100).toFixed(0)+'%';
    if(!this.matrix||!this.enabled||this.mode!=='align'||this.tool==='navigate')return;const p=M.origin(this.matrix),o=this.screen(p);if(!o)return;const length=Math.max(1,85*p[2]/(this.camera.fx*this.zoom));ctx.font='bold 12px Arial';ctx.lineWidth=2.5;
    for(let i=0;i<3;i++){const a=M.axis(this.matrix,i,this.space);ctx.strokeStyle=ctx.fillStyle=colors[i];
      if(this.tool==='translate'){let end=this.screen(M.add(p,M.scale(a,length)));if(!end)continue;let depth=false;if(M.norm(M.sub(end,o))<22){end=M.add(o,[28+7*i,30+7*i]);depth=true;}ctx.setLineDash(depth?[3,3]:[]);ctx.beginPath();ctx.moveTo(...o);ctx.lineTo(...end);ctx.stroke();ctx.setLineDash([]);ctx.beginPath();ctx.arc(...end,5,0,Math.PI*2);ctx.fill();ctx.fillText('XYZ'[i]+(depth?' ↕':''),end[0]+9,end[1]-6);this.handles.push({i,points:[o,end],depth});
      }else{const helper=Math.abs(a[2])<.9?[0,0,1]:[0,1,0],u=M.unit(M.cross(a,helper)),v=M.cross(a,u),points=[];ctx.beginPath();for(let k=0;k<=96;k++){const t=k/96*Math.PI*2;const point=this.screen(M.add(p,M.scale(M.add(M.scale(u,Math.cos(t)),M.scale(v,Math.sin(t))),length*.85)));if(!point)continue;points.push(point);if(points.length===1)ctx.moveTo(...point);else ctx.lineTo(...point);}ctx.stroke();if(points.length){ctx.fillText('XYZ'[i],points[Math.min(12,points.length-1)][0]+4,points[Math.min(12,points.length-1)][1]-4);this.handles.push({i,points});}}
    }ctx.fillStyle='#ddd';ctx.fillRect(o[0]-3,o[1]-3,6,6);
  }
  hit(point){let best=null,minimum=10;for(const handle of this.handles){for(let j=1;j<handle.points.length;j++){const d=distanceToSegment(point,handle.points[j-1],handle.points[j]);if(d<minimum){best=handle;minimum=d;}}}return best;}
  down(e){if(!this.camera)return;const point=this.point(e);if(e.button===1||(e.button===0&&(this.tool==='navigate'||e.altKey))){this.drag={navigation:true,point,pan:[...this.pan]};this.canvas.setPointerCapture(e.pointerId);return;}if(e.button!==0||!this.enabled||this.mode!=='align')return;const handle=this.hit(point);if(!handle)return;e.preventDefault();this.started?.();const matrix=M.copy(this.matrix),p=M.origin(matrix),a=M.axis(matrix,handle.i,this.space),r=M.ray(this.imagePoint(point),this.camera);this.drag={point,matrix,handle,p,a,parameter:handle.depth?null:M.axisParameter(r,p,a),vector:M.planeVector(r,p,a),space:this.space,tool:this.tool};this.canvas.setPointerCapture(e.pointerId);}
  move(e){const point=this.point(e);if(!this.drag){this.canvas.style.cursor=this.hit(point)?'grab':this.tool==='navigate'?'grab':'default';return;}const d=this.drag;if(d.navigation){this.pan=M.add(d.pan,M.sub(point,d.point));this.fitMode=false;this.draw();return;}const r=M.ray(this.imagePoint(point),this.camera),fine=e.shiftKey ? 0.1 : 1;let matrix;
    if(d.tool==='translate'){const parameter=M.axisParameter(r,d.p,d.a);let amount;if(d.parameter!=null&&parameter!=null&&!d.handle.depth)amount=(parameter-d.parameter)*fine;else amount=(point[1]-d.point[1])*d.p[2]/(this.camera.fy*this.zoom)*fine;matrix=M.translate(d.matrix,d.handle.i,amount,d.space);}else{const vector=M.planeVector(r,d.p,d.a);let angle=d.vector&&vector?M.signedAngle(d.vector,vector,d.a):((point[0]-d.point[0])-(point[1]-d.point[1]))*.012;matrix=M.rotate(d.matrix,d.handle.i,angle*fine,d.space);}
    this.matrix=matrix;this.changed(matrix);this.draw();this.preview(matrix);
  }
  up(e){if(!this.drag)return;const d=this.drag;this.drag=null;if(this.canvas.hasPointerCapture(e.pointerId))this.canvas.releasePointerCapture(e.pointerId);if(!d.navigation)this.finished(this.matrix);}
  preview(matrix){if(!this.camera||!this.geometry)return;this.overlay.width=this.camera.width;this.overlay.height=this.camera.height;const ctx=this.overlay.getContext('2d');ctx.strokeStyle='#efce50';ctx.lineWidth=2/this.zoom;const points=this.geometry.points.map(p=>M.project(M.transform(matrix,p),this.camera)).filter(Boolean);if(points.length<3)return;points.sort((a,b)=>a[0]-b[0]||a[1]-b[1]);const turn=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);const half=arr=>{const h=[];for(const p of arr){while(h.length>1&&turn(h.at(-2),h.at(-1),p)<=0)h.pop();h.push(p);}return h;};const hull=[...half(points).slice(0,-1),...half([...points].reverse()).slice(0,-1)];ctx.beginPath();hull.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.stroke();}
  clearPreview(){this.overlay.getContext('2d').clearRect(0,0,this.overlay.width,this.overlay.height);}
}
