import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const out=path.join(process.cwd(),'outputs','mesh-ui-'+Date.now());await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--proxy-server=direct://']});
const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
async function state(){return page.evaluate(async()=>await(await fetch('/api/state')).json());}
async function request(route,body){const result=await page.evaluate(async({route,body})=>{const r=await fetch('/api/'+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return{ok:r.ok,data:await r.json()};},{route,body});assert.ok(result.ok,JSON.stringify(result.data));return result.data;}
async function applyScale(){await page.locator('#meshScale').fill('10');await page.locator('#scaleMesh').click();await page.locator('#invalidation').waitFor({state:'visible'});const response=page.waitForResponse(r=>r.url().endsWith('/api/resource')&&r.request().method()==='POST');await page.locator('[data-decision="clear"]').click();assert.ok((await response).ok());await page.waitForTimeout(250);}
try{
 await page.goto(process.env.TRACKER_URL||'http://127.0.0.1:8767');await request('create',{name:'Mesh fixes',directory:out+'/project'});await request('resource',{kind:'source',path:process.cwd()+'/testdata/phone_short/frames'});await request('resource',{kind:'mesh',path:process.cwd()+'/testdata/phone_short/phone.glb'});await page.reload();await page.waitForFunction(()=>document.querySelector('#projectName').textContent==='Mesh fixes');
 const first=(await state()).project;assert.equal(first.mesh.source_units,'meters');assert.ok(first.mesh.dimensions_mm[2]>990);assert.deepEqual(first.drafts['0'].matrix.slice(0,3).map(r=>r.slice(0,3)),[[1,0,0],[0,1,0],[0,0,1]]);assert.ok(first.drafts['0'].matrix[2][3]>0);await page.locator('[data-context="mesh"]').click();await applyScale();const second=(await state()).project.mesh;await applyScale();const third=(await state()).project.mesh;for(let i=0;i<3;i++)assert.ok(Math.abs(third.dimensions_mm[i]/first.mesh.dimensions_mm[i]-100)<.01);
 // Use realistic dimensions before exercising numeric edits and late image replies.
 await request('resource',{kind:'mesh',path:first.mesh.source,options:{dimensions:[75,11,160],center:true},invalidation:'clear'});await page.reload();await page.waitForFunction(()=>document.querySelector('#projectName').textContent==='Mesh fixes');await page.locator('[data-mode="align"]').click();
 await page.route('**/api/frame?*',async route=>{await new Promise(resolve=>setTimeout(resolve,250));await route.continue();});
 for(const v of [10,20,30,40,50]){await page.locator('#tx').fill(String(v));await page.waitForTimeout(80);}await page.waitForTimeout(1500);assert.equal((await state()).project.drafts['0'].matrix[0][3],50);assert.equal(Number(await page.locator('#tx').inputValue()),50);await page.waitForFunction(()=>document.querySelector('#frameImage').complete&&document.querySelector('#frameImage').naturalWidth===1920);assert.ok((await page.locator('#frameImage').getAttribute('src')).startsWith('blob:'));await page.screenshot({path:out+'/mesh.png'});assert.deepEqual(errors,[]);await fs.writeFile(out+'/report.json',JSON.stringify({passed:true,checks:['GLB meters converted to mm','neutral centered load pose','two relative scales accumulate','latest numeric pose survives delayed image replies'],first:first.mesh.dimensions_mm,second:second.dimensions_mm,third:third.dimensions_mm,errors},null,2));console.log('PASS '+out);
}finally{await browser.close();}
