import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=process.cwd(),out=path.join(root,'outputs','ui-redesign-'+Date.now());await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--proxy-server=direct://']});
const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const trackedCount=Number(process.env.TRACKER_TEST_FRAMES||8);
assert.ok(trackedCount>=8&&trackedCount<=61);
const checks=[];const report=()=>fs.writeFile(path.join(out,'report.json'),JSON.stringify({checks,errors,project:out+'/Redesign',passed:!errors.length},null,2));
async function state(){return page.evaluate(async()=>await(await fetch('/api/state')).json());}
async function until(fn,timeout=180000){const end=Date.now()+timeout;while(Date.now()<end){const s=await state();if(s.error)throw new Error(s.error);if(fn(s))return s;await page.waitForTimeout(150);}throw new Error('State timeout');}
async function idle(){return until(s=>!s.busy);}
async function click(id,route){const [r]=await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/'+route)&&r.request().method()==='POST'),page.locator('#'+id).click()]);if(!r.ok())throw new Error(await r.text());return r.json();}
async function browse(target,name=''){await page.locator('#browser').waitFor({state:'visible'});await page.locator('#browsePath').fill(target);await page.locator('#browseGo').click();await page.waitForFunction(target=>document.querySelector('#browsePath').value===target&&document.querySelector('#breadcrumbs').textContent.includes(target.split('/').filter(Boolean).pop()),target);await page.waitForTimeout(100);if(name){await page.locator('#browseName').fill(name);}await page.locator('#browseSelect').click();await page.locator('#browser').waitFor({state:'hidden'});}
async function upload(files){const chooser=page.waitForEvent('filechooser');await page.locator('#uploadResource').click();await(await chooser).setFiles(files);}
async function select(context){await page.locator(`[data-context="${context}"]`).click();}
async function importPose(){await page.locator('#importPose').click();await browse(root+'/testdata/phone_short','initial_pose.npy');await until(s=>!!s.project.drafts['0']);}
async function gizmoDrag(axis,space,rotate=false){await page.locator(`[data-space="${space}"]`).first().click();await page.locator(`[data-tool="${rotate?'rotate':'translate'}"]`).click();await page.waitForTimeout(250);const coords=await page.evaluate(async({axis,space,rotate})=>{const M=await import('/pose-math.js');const s=await(await fetch('/api/state')).json(),c=s.project.camera,m=s.project.drafts['0'].matrix,p=M.origin(m),a=M.axis(m,axis,space);const t=new DOMMatrix(document.querySelector('#imageStage').style.transform);const rect=document.querySelector('#gizmo').getBoundingClientRect();const project=v=>{const uv=M.project(v,c);return[rect.x+t.e+uv[0]*t.a,rect.y+t.f+uv[1]*t.d];};const length=85*p[2]/(c.fx*t.a);if(rotate){const helper=Math.abs(a[2])<.9?[0,0,1]:[0,1,0],u=M.unit(M.cross(a,helper)),v=M.cross(a,u);return [.55,.95].map(angle=>project(M.add(p,M.scale(M.add(M.scale(u,Math.cos(angle)),M.scale(v,Math.sin(angle))),length*.85))));}const start=project(M.add(p,M.scale(a,length*.8)));return[start,[start[0]+18,start[1]+9]];},{axis,space,rotate});await page.mouse.move(...coords[0]);await page.mouse.down();await page.mouse.move(...coords[1],{steps:12});await page.mouse.up();await page.waitForTimeout(650);}
try{
 await page.goto(process.env.TRACKER_URL||'http://127.0.0.1:8765');await page.locator('#projectName').waitFor();await page.locator('summary').filter({hasText:/^File$/}).click();await page.locator('#newProject').click();await page.locator('#name').fill('Redesign');await page.locator('#chooseProjectFolder').click();await browse(out);await click('create','create');checks.push('new empty project via folder browser');
 await select('source');await page.locator('#browseResource').click();await browse(root+'/testdata/phone_short/frames');await until(s=>s.project.source.frames.length===61);checks.push('server sequence browser');
 await select('mesh');const chooser=page.waitForEvent('filechooser');await page.locator('#uploadResource').click();await(await chooser).setFiles(root+'/testdata/phone_short/phone_mm.ply');await until(s=>!!s.project.mesh);checks.push('native mesh upload');
 await select('camera');await page.locator('#fx').fill('1867');await page.locator('#fy').fill('1867');await click('camera','resource');await importPose();await page.waitForFunction(()=>document.querySelector('#frameImage').naturalWidth===1920);
 const before=(await state()).project.drafts['0'].matrix;await gizmoDrag(0,'global');let changed=(await state()).project.drafts['0'].matrix;assert.notDeepEqual(changed,before);assert.equal(changed[1][3],before[1][3]);checks.push('global constrained translation');
 await importPose();await gizmoDrag(0,'local');changed=(await state()).project.drafts['0'].matrix;assert.notEqual(changed[1][3],before[1][3]);checks.push('local constrained translation');
 await importPose();await gizmoDrag(2,'global',true);changed=(await state()).project.drafts['0'].matrix;assert.notDeepEqual(changed.slice(0,3).map(r=>r.slice(0,3)),before.slice(0,3).map(r=>r.slice(0,3)));assert.deepEqual(changed.slice(0,3).map(r=>r[3]),before.slice(0,3).map(r=>r[3]));checks.push('rotation ring and numeric synchronization');
 await importPose();await click('refine','refine');await idle();await page.waitForFunction(()=>!document.querySelector('#accept').disabled);await click('accept','accept');checks.push('GPU refine and accept');
 await page.locator('[data-mode="track"]').click();const box=await page.locator('#timeline').boundingBox();const step=(box.width-127)/61;await page.mouse.move(box.x+115+step*3.5,box.y+14);await page.mouse.down();await page.mouse.move(box.x+115+step*8.5,box.y+14,{steps:12});await page.mouse.up();assert.equal(await page.locator('#rangeStart').inputValue(),'3');assert.equal(await page.locator('#rangeEnd').inputValue(),'8');checks.push('timeline direct range selection');
 // Start from the accepted anchor for the actual inference check.
 await page.locator('#rangeStart').fill('0');await page.locator('#rangeEnd').fill('3');await click('track','track');await idle();assert.equal(Object.keys((await state()).project.poses).length,4);checks.push('GPU range tracking');
 await page.locator('#rangeEnd').fill(String(trackedCount-1));await click('track','track');await until(s=>(s.project.job?.completed.length||0)>=1);await click('cancel','cancel');let stopped=await idle();assert.equal(stopped.project.job.status,'cancelled');const committed=structuredClone(stopped.project.poses);
 await page.locator('summary').filter({hasText:/^File$/}).click();await page.locator('#openProject').click();const opened=page.waitForResponse(r=>r.url().endsWith('/api/open')&&r.request().method()==='POST');await browse(out+'/Redesign','project.json');assert.ok((await opened).ok());await page.waitForFunction(()=>!document.querySelector('#resume').disabled);await click('resume','resume');let resumed=await idle();assert.equal(resumed.project.job.completed.length,trackedCount);for(const index of stopped.project.job.completed)assert.deepEqual(resumed.project.poses[index],committed[index]);checks.push('cancel, Open Project dialog, resume preserves committed poses');
 const outside=structuredClone(resumed.project.poses[trackedCount-1]);await page.locator('#rangeStart').fill('2');await page.locator('#rangeEnd').fill('3');await click('trackBackward','track');await idle();assert.deepEqual((await state()).project.poses[trackedCount-1],outside);checks.push('backward range preserves outside poses');

 await select('mesh');await page.locator('#replaceResource').click();await browse(root+'/testdata/phone_short','phone_mm.ply');await page.locator('#invalidation').waitFor({state:'visible'});await page.locator('[data-decision="cancel"]').click();assert.equal(Object.keys((await state()).project.poses).length,trackedCount);checks.push('resource replacement cancellation preserves results');
 await page.locator('#replaceResource').click();await browse(root+'/testdata/phone_short','phone_mm.ply');await page.locator('[data-decision="preserve"]').click();await until(s=>s.project.solutions.length===1&&Object.keys(s.project.poses).length===0);await select('solutions');await page.locator('[data-solution]').first().click();await until(s=>Object.keys(s.project.poses).length===trackedCount);checks.push('preserved solution restores original resource context');
 await select('source');await page.locator('#replaceResource').click();await browse(root+'/testdata/phone_short/frames');await page.locator('[data-decision="preserve"]').click();await until(s=>Object.keys(s.project.poses).length===0);checks.push('replace source with explicit invalidation');
 await select('solutions');await page.locator('[data-solution]').last().click();await until(s=>Object.keys(s.project.poses).length===trackedCount);

 const original=(await state()).project.source.frames.slice(0,2);const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=1920;c.height=1080;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(700,300,200,300);return c.toDataURL().split(',')[1];});
 const maskFiles=original.map(f=>({name:path.parse(f.filename).name+'.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')}));
 for(const kind of ['object_mask','occlusion_mask']){await select(kind);await upload(maskFiles);await until(s=>Object.keys(s.project.masks[kind]).length===2);assert.ok((await state()).project.mask_sources[kind].directory.includes('/cache/assets/'+kind+'/'));}
 await page.locator('#frameNumber').fill('0');await page.locator('#frameNumber').press('Tab');await page.locator('summary').filter({hasText:'Masks'}).click();await page.locator('#showObjectMask').uncheck();await page.locator('#showOcclusionMask').check();await page.waitForFunction(()=>document.querySelector('#frameImage').complete&&document.querySelector('#frameImage').naturalWidth===1920);await page.locator('#showObjectMask').check();await page.locator('#showOcclusionMask').uncheck();await page.locator('summary').filter({hasText:'Masks'}).click();checks.push('multiple native uploads and independent mask layers');
 await select('source');await upload(original.map(f=>f.path));await page.locator('[data-decision="preserve"]').click();await until(s=>s.project.source.frames.length===2);assert.ok((await state()).project.source.path.includes('/cache/assets/source/'));await select('solutions');await page.locator('[data-solution]').last().click();await until(s=>s.project.source.frames.length===61&&Object.keys(s.project.poses).length===trackedCount);checks.push('multiple source uploads and solution context restoration');
 for(const kind of ['object_mask','occlusion_mask']){await select(kind);await click('clearMasks','masks');}
 await select('exports');const exported=await click('export','export');assert.equal(exported.files.length,4);await click('preview','preview');await idle();assert.ok((await state()).project.last_preview);await page.waitForFunction(()=>document.querySelectorAll('.exportLink').length>=5);checks.push('pose exports and MP4 preview download links');
 await page.locator('[data-mode="align"]').click();await page.locator('#fit').click();await page.screenshot({path:path.join(out,'alignment-1440.png')});
 await page.locator('#viewport').click({position:{x:20,y:20}});const frameBefore=Number(await page.locator('#frameNumber').inputValue());await page.keyboard.press('ArrowRight');await page.waitForFunction(n=>Number(document.querySelector('#frameNumber').value)===n,frameBefore+1);await page.keyboard.press('Control+s');await page.keyboard.press('Space');await page.waitForTimeout(300);await page.keyboard.press('Space');checks.push('frame, playback and save shortcuts');
 await page.locator('[data-mode="review"]').click();await page.locator('#toggleDiagnostics').click();await page.locator('#scoreGraph').click({position:{x:15,y:35}});await page.locator('#oneToOne').click();assert.equal(await page.locator('#zoomLabel').textContent(),'100%');await page.locator('#fit').click();checks.push('review graphs and fit/1:1');
 const split=await page.locator('#leftSplitter').boundingBox();await page.mouse.move(split.x+2,split.y+60);await page.mouse.down();await page.mouse.move(split.x+32,split.y+60,{steps:6});await page.mouse.up();const layout=await page.evaluate(()=>localStorage.getItem('tracker.layout'));assert.ok(layout.includes('left'));checks.push('persistent splitters');
 await page.screenshot({path:path.join(out,'workspace-1440.png')});await page.setViewportSize({width:1920,height:1080});await page.waitForTimeout(300);await page.screenshot({path:path.join(out,'workspace-1920.png')});
 await page.reload();await page.waitForFunction(()=>document.querySelector('#projectName').textContent==='Redesign');assert.equal(await page.evaluate(()=>localStorage.getItem('tracker.layout')),layout);checks.push('reload with saved project/layout');
 assert.equal(errors.length,0,errors.join('\n'));await report();console.log('PASS '+out);
}catch(e){errors.push(e.message);await page.screenshot({path:path.join(out,'failure.png')});await report();throw e;}finally{await browser.close();}
